---
- name: create change from servicenow
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create change
    servicenow.itsm.change_request:
      type: "{{ snow_chg_type }}"
      state: new
      requested_by: admin
      short_description: "{{ snow_chg_short_desc }}"
      description: "{{ snow_chg_desc }}"
      priority: "{{ snow_chg_prio }}"
      risk: "{{ snow_chg_risk }}"
      impact: "{{ snow_chg_impact }}"
      assignment_group: "{{ snow_chg_assign }}"
    register: chg_number

  - name: display change number
    debug:
       msg: "A New Change Has been raised with number - {{ chg_number.record.number }}"
