---
- name: Change motd after DR
  hosts: all
  vars:
    is_active: ""
  tasks:
    - name: Update the MOTD with failover information
      ansible.builtin.copy:
        content: "Last Failover Completed at {{ ansible_date_time.iso8601 }}. Instance status: {{ is_active }}"
        dest: /etc/motd
        owner: root
        group: root
        mode: '644'
