---
- hosts: all
  gather_facts: true

  tasks:
    - name: Wait for VMs to be avaialble
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 60

    - name: Ping each host
      ansible.builtin.ping:
      register: ping_pong

    # - name: Gather facts on listening ports
    #   community.general.listen_ports_facts:

    # - name: List TCP ports
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_facts }}"

    - name: Get security group port information
      amazon.aws.ec2_security_group_info:
        filters:
          vpc-id: "{{ vpc_id }}"

    - name: List SC Group config
      ansible.builtin.debug:
        msg: "{{ vpc-id }}"
