---
- hosts: all
  gather_facts: true

  tasks:
    - name: Wait for VMs to be avaialble
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 60

    - name: Ping each host
      ansible.builtin.ping:
      register: ping_pong

    - name: Get security group port information
      amazon.aws.ec2_security_group_info:
        region: eu-west-1
      delegate_to: localhost
      register: vpc_info

    - name: List ports
      ansible.builtin.set_fact:
        open_tcp_ports: "{{ item.ip_permissions | map(attribute='from_port') | list }}"
      loop: "{{ vpc_info.security_groups | selectattr('group_name', 'equalto', 'aap-sg') | list }}"

    - name: Assert 5432 postgreSQL port is open
      ansible.builtin.assert:
        that:
          - "{{ open_tcp_ports is contains('5432') }}"
