---
- hosts: all
  gather_facts: true

  tasks:
    - name: Wait for VMs to be avaialble
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 60

    - name: Ping each host
      ansible.builtin.ping:
      register: ping_pong

    # - name: Gather facts on listening ports
    #   community.general.listen_ports_facts:

    # - name: List TCP ports
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_facts }}"

    - name: Get security group port information
      amazon.aws.ec2_security_group_info:
        region: eu-west-1
      delegate_to: localhost
      register: vpc_info

    - name: List SC Group config
      ansible.builtin.debug:
        msg: "{{ vpc_info.security_groups | selectattr('group_name', 'equalto', 'app-sg') }}"
